M48
; DRILL file {KiCad 9.0.2} date 2025-07-09T02:03:54-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-09T02:03:54-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X161.205Y-86.7
X167.4Y-113.2
X168.205Y-86.7
X174.4Y-113.2
T2
X150.0Y-74.5
M30
